### ISSUE TITLE
Sensor Read Task with 100 Hz

### ISSUE THREAD

**Issue by jbinz** [catsystems/cats-embedded#73]
As the temperature is not that important anymore, run the sensor read task with 100 Hz and read the temperature from the accelerometer for logging purposes ( is less exact). Then, the temperature of the barometer doesnt need to be read out.

**Comment by l-jost** [comment]
This is not true, the temperature is used internally to calculate the air pressure. Since during a flight the temperature can change like 20°C as seen on the Helvetia flight, it is important to keep that information. 
![image](https://user-images.githubusercontent.com/47953330/177324956-d553231b-40a4-41b3-81f4-7f70c3cb20c5.png)

**Comment by tonuonu** [comment]
I'd like to understand the Helvetia flight data better. How was the MS5607 mounted on that rocket?
The MS5607 temperature output is the sensor die temperature, not ambient air. For a typical installation where the sensor is soldered to a PCB inside an electronics bay, the thermal mass creates a time constant measured in minutes. Even with large ambient temperature swings, the die should barely move during a 60-90 second flight.
If logged temperature showed 20°C change, was the sensor somehow exposed to airflow, or was this a particularly long flight? Or perhaps most of that change happened on the ground before/after flight rather than during? Sorry, I am just curious to understand and correct my thinking if I am wrong.
